version: '1'

services:
  web:
    build: .
    command:  sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app

#   db:
#     image: postgres
#     environment:
#       POSTGRES_DATABASE: pharmadb
#       POSTGRES_PASSWORD: admin
#     volumes:
#       - ./db:/var/lib/postgresql/data


# volumes:
#   web:
#   db: