version: '3.9'
services:
  api-pharma:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - pharmadb
    develop:
      watch:
        - action: rebuild
          path: .  
  pharmadb:
    image: postgres:latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgresqlVolume:/var/lib/postgres
      - postgresqlConfig:/etc/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
volumes:
  postgresqlVolume:
  postgresqlConfig: